**ARRAY - ds consisting of elements each identified by at least one array index or key**

Numpy - fundamental package for scientific computing in python
      - stores list of numerical vectors andmatrices in the form of arrays
      - the NumPy package has a large set of routines (built-in fns) for creating, manipulating and transforming NumPy arrays

In [1]:
# Creating a one dimensional array using a list
# using numpy.array() function

import numpy as np

my_list = [1,2,3,4]

Oned_arr = np.array(my_list)

Oned_arr #one dimensional array

array([1, 2, 3, 4])

In [2]:
Oned_arr = np.array(my_list, dtype = 'int32')

Oned_arr

array([1, 2, 3, 4], dtype=int32)

In [3]:
# atrributes of an array

print("Array:", Oned_arr)

print("Data type:", type(Oned_arr))

print("Shape of an array:", Oned_arr.shape) # the shape of an array is similar to an order of a matrix

print("Size of each value in an array in bytes:", Oned_arr.itemsize)

print("Total no of bytes of an array:", Oned_arr.nbytes)

print("Data type of an array:", Oned_arr.dtype)

print("Dimension of an array:", Oned_arr.ndim)

# here the shape (4,) means the array is indexed by a single index which runs from 0 to 4

Array: [1 2 3 4]
Data type: <class 'numpy.ndarray'>
Shape of an array: (4,)
Size of each value in an array in bytes: 4
Total no of bytes of an array: 16
Data type of an array: int32
Dimension of an array: 1


In [4]:
# printing the values of a 1-dimensional array using a for loop

print("The array is ")

for i in Oned_arr:

    print(i, end = ' ')

The array is 
1 2 3 4 

In [5]:
# converting a 1-dimensional array to a list

Oned_arr = Oned_arr.tolist()

print(Oned_arr)

print(type(Oned_arr))

[1, 2, 3, 4]
<class 'list'>


In [6]:
# creating a 2D array 

my_mat = [[1,2,3],[4,5,6],[7,8,9]]

array_2D = np.array(my_mat, dtype = 'int32')

array_2D

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]], dtype=int32)

In [7]:
# atrributes of an array

print("Array:", array_2D)

print("Data type:", type(array_2D))

print("Shape of an array:", array_2D.shape) #the shape of an array is a tuple of integers giving the size of the array along each dimension.

print("Size of each value in an array in bytes:", array_2D.itemsize)

print("Total no of bytes of an array:", array_2D.nbytes)

print("Data type of an array:", array_2D.dtype)

print("Dimension of an array:", array_2D.ndim) # it is a 2D array since it requires the index of a row and column to access any element.

Array: [[1 2 3]
 [4 5 6]
 [7 8 9]]
Data type: <class 'numpy.ndarray'>
Shape of an array: (3, 3)
Size of each value in an array in bytes: 4
Total no of bytes of an array: 36
Data type of an array: int32
Dimension of an array: 2


In [8]:
# looping through a 2D array

lst = []

for i in array_2D:
    for j in i:
        print(j, end = ' ')
    print() # gives an empty line as an output

1 2 3 
4 5 6 
7 8 9 


In [9]:
# converting a 2D array to a list using a .tolist() fn
array_2D = array_2D.tolist()

print(array_2D)

print(type(array_2D))

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]
<class 'list'>


In [10]:
# creating an array using a numpy .arange() fn

a_range = np.arange(6)

print(a_range)

[0 1 2 3 4 5]


In [11]:
a_range1 = np.arange(0,11,2)

print(a_range1)

[ 0  2  4  6  8 10]


In [12]:
# reshaping an array using the .reshape() fn

array = np.arange(6).reshape(3, 2) #3 rows and 2 columns

print(array, "\n")

[[0 1]
 [2 3]
 [4 5]] 



In [13]:
# constructing a 3D array

array = np.arange(8).reshape(2,2,2)

print(array)

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


In [14]:
z = np.arange(0, 16, 2).reshape(2,2,2)
print(z, "\n")

z = z.reshape(-1)  # creates a 1D array
print(z)
print(z.shape)
print(z.ndim, "\n")

[[[ 0  2]
  [ 4  6]]

 [[ 8 10]
  [12 14]]] 

[ 0  2  4  6  8 10 12 14]
(8,)
1 



In [15]:
z = np.arange(0, 16, 2).reshape(2,2,2)
print(z, "\n")

z = z.reshape(1, -1)  # creates a 2D array with a single row
print(z)
print(z.shape)
print(z.ndim, "\n")

[[[ 0  2]
  [ 4  6]]

 [[ 8 10]
  [12 14]]] 

[[ 0  2  4  6  8 10 12 14]]
(1, 8)
2 



In [16]:
z = np.arange(0, 16, 2).reshape(2,2,2)
print(z, "\n")

z = z.reshape(-1, 1)  # creates a 2D array with a single row
print(z)
print(z.shape)
print(z.ndim, "\n")

[[[ 0  2]
  [ 4  6]]

 [[ 8 10]
  [12 14]]] 

[[ 0]
 [ 2]
 [ 4]
 [ 6]
 [ 8]
 [10]
 [12]
 [14]]
(8, 1)
2 



In [17]:
# Creating different types of arrays

import numpy as np

np.random.randint(1, 100) # generating a ranfom integer between 1 and 100

55

In [18]:
print("************One dimensional********\n")

print(np.random.randint(1, 100, size = 10), "\n") # will have a shape of 10

print("************Two dimensional********\n")

print(np.random.randint(1, 100, size = (3,4)), "\n") # 2D array with a shape of (3,4)

************One dimensional********

[61 19 44 13 46 11 89 46 53  5] 

************Two dimensional********

[[41 92 27 75]
 [57 86 57 94]
 [90 71  5 82]] 



In [19]:
print("************Three dimensional********\n")

print(np.random.randint(1, 100, size = (3,2,2)), "\n") # will have a shape of (3,2,2)

print("************Four dimensional********\n")

print(np.random.randint(1, 100, size = (4,3,32,64)), "\n") # 2D array with a shape of (4,3,32,64)

************Three dimensional********

[[[ 7 34]
  [98 93]]

 [[ 3 89]
  [20 87]]

 [[90 98]
  [96 36]]] 

************Four dimensional********

[[[[63 44 10 ... 61 76 50]
   [39 67 14 ... 39 78 48]
   [ 5 62  4 ... 76 32 52]
   ...
   [15 71 99 ... 66 73 22]
   [98 16 39 ... 63 90 84]
   [62 18 79 ... 79 14 24]]

  [[73 71 17 ... 58 55 31]
   [23 54 66 ... 26 48 67]
   [57 52 97 ... 23 80 47]
   ...
   [19 19  9 ... 89  5 85]
   [93 66 76 ... 55 30  3]
   [36 35 49 ... 61  8 44]]

  [[86 19 72 ... 21 39 52]
   [76 16 55 ... 67 81 89]
   [84 20 22 ... 34 35 16]
   ...
   [85 86 51 ... 87 44 41]
   [99 27 96 ... 30 72 24]
   [81  1 55 ... 41 89 73]]]


 [[[49 48 17 ... 39 61 96]
   [54 18 70 ... 75 98 34]
   [38 89 43 ... 58 86 73]
   ...
   [93 84 46 ... 73 55 34]
   [46 13 76 ...  9 54 19]
   [27 41 35 ... 65  5 29]]

  [[62 68 78 ... 82 15 65]
   [48 71 52 ... 94 19 92]
   [69 76 89 ... 12  8 29]
   ...
   [ 8 96 54 ... 88  6 19]
   [80 72 60 ... 27 42 13]
   [70 48 81 ... 55  7 53]]

In [20]:
np.random.rand(5)   # creating a 1D array of 5 number between 0 and 1

array([0.25202905, 0.48449127, 0.49661736, 0.65921064, 0.17681761])

In [21]:
np.random.rand(5,5)   # creating 2D array of random numbers between 0 and 1 of shape (5,5)

array([[0.84343802, 0.2999878 , 0.62982934, 0.30167419, 0.49013615],
       [0.77941032, 0.05902832, 0.02661915, 0.75805499, 0.26096912],
       [0.84515629, 0.96667247, 0.22509018, 0.01007859, 0.64757826],
       [0.41062513, 0.24628667, 0.39130005, 0.21873984, 0.09599841],
       [0.37684093, 0.77075245, 0.71452752, 0.02892415, 0.91526891]])

In [22]:
# creating a 1D array of saamples from the "standard normal" distribution between 0 and 1

np.random.randn(10)

array([ 0.45646256, -0.08857907, -0.43016568, -0.76468921,  0.03411897,
       -0.31117583,  0.97775275,  0.02802175, -0.17308091, -1.37594488])

FUNCTIONS TO CREATE ARRAYS OF DIFFERENT TYPES

In [23]:
np.zeros(5)  # creates a new array of given shape and type, filled with zeros

array([0., 0., 0., 0., 0.])

In [24]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [25]:
np.ones(5)   #creates an array filled with ones

array([1., 1., 1., 1., 1.])

In [26]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [27]:
np.eye(4)   # return a 2D array with ones on the diagonal and zeros somewhere

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [28]:
np.full((3,3), 7)  # return a new array filled with a 'filled value'

array([[7, 7, 7],
       [7, 7, 7],
       [7, 7, 7]])

In [29]:
np.diag([1,2,3])  # constructs a diagonal array or extract diagonal values of a multi-dimensional

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [30]:
np.linspace(0,5,10)   # returns an evenly spaced numbers over a specified interval

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

**DATA TYPE CONVERSION OF AN ARRAY**

In [31]:
randarr = np.random.randint(0, 100, 10)

In [32]:
randarr.dtype

dtype('int32')

In [33]:
randarr.astype('int64')

array([21, 69, 63, 28, 13, 69, 76, 57, 36, 43])

In [34]:
randarr.astype('float64')

array([21., 69., 63., 28., 13., 69., 76., 57., 36., 43.])

In [35]:
randarr.astype('str')

array(['21', '69', '63', '28', '13', '69', '76', '57', '36', '43'],
      dtype='<U11')

In [36]:
randarr.astype('complex128')

array([21.+0.j, 69.+0.j, 63.+0.j, 28.+0.j, 13.+0.j, 69.+0.j, 76.+0.j,
       57.+0.j, 36.+0.j, 43.+0.j])

**ACCESSING ARRAY VALUES**

In [37]:
# accessing and slicing a 1D array values

import numpy as np

arr_1D = np.arange(1,20,2)

arr_1D

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [38]:
arr_1D[8]   # array indexing

np.int64(17)

In [39]:
arr_1D[-1]  # negative indexing 

np.int64(19)

In [40]:
arr_1D[1:5]   # array slicing - but excludes the 5th index

array([3, 5, 7, 9])

In [41]:
arr_1D[0:5]  # - excludes the 5th index

array([1, 3, 5, 7, 9])

In [42]:
arr_1D[:6]

array([ 1,  3,  5,  7,  9, 11])

In [43]:
arr_1D[0] = 111  # changing an array value
arr_1D

array([111,   3,   5,   7,   9,  11,  13,  15,  17,  19])

In [44]:
arr_1D[5:] = 100  # changing array values from the 5th index
arr_1D

array([111,   3,   5,   7,   9, 100, 100, 100, 100, 100])

In [45]:
arr_1D[0] = 112.12  # if we add a float value to an array with integer
             # values, only the integer part will be included in the list
arr_1D

array([112,   3,   5,   7,   9, 100, 100, 100, 100, 100])

In [46]:
# accessing and slicing a 2D array values

arr_2D = np.array([[5,10,15],[20,25,30],[35,40,45]])

arr_2D

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [47]:
arr_2D[0]  # array indexing

array([ 5, 10, 15])

In [48]:
arr_2D[0][2] # accessing a value in a given row

# in this case first row, last value

np.int64(15)

In [49]:
arr_2D[1,2]  # similar to the example in the cell above

np.int64(30)

In [50]:
arr_2D[:2, 1:]  # accessing values in a portion of an array through slicing

array([[10, 15],
       [25, 30]])

In [51]:
arr_2d = np.arange(50).reshape(5, 10)
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [52]:
arr_2d[0:4, 1:4]

array([[ 1,  2,  3],
       [11, 12, 13],
       [21, 22, 23],
       [31, 32, 33]])

In [53]:
# CREATING AN ARRAY VIEW AND AN ARRAY COPY

# array view is a way to access the same data as an existing array without copying it

arr = np.arange(0, 10)

arr # original array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [54]:
arr_view = arr[5:]  # array view creation

arr_view

array([5, 6, 7, 8, 9])

In [55]:
np.shares_memory(arr, arr_view)  # determining if two arrays share memory reference

True

In [56]:
arr_view[:] = 100

arr_view

array([100, 100, 100, 100, 100])

In [57]:
arr  # changes in the view also apply to the original array

array([  0,   1,   2,   3,   4, 100, 100, 100, 100, 100])

In [58]:
# creating an array copy

arr

array([  0,   1,   2,   3,   4, 100, 100, 100, 100, 100])

In [59]:
arr_copy = arr[5:].copy() # creating an array copy

arr_copy

array([100, 100, 100, 100, 100])

In [60]:
np.shares_memory(arr, arr_copy)  # determining if two arrays share memory reference

False

In [61]:
arr_copy[:] = 120

arr_copy # changes made to the copy array will not affect the original array

array([120, 120, 120, 120, 120])

In [62]:
arr # original array

array([  0,   1,   2,   3,   4, 100, 100, 100, 100, 100])

**NUMPY OPERATIONS**

In [99]:
# Time taken to perform operations with Numpy array is much lesser than the time taken by python built-in sequence

x = range(1, 1000)

%timeit [2**i for i in x]

# %timeit gives us the time taken to execute a python statement or expression

806 μs ± 117 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [100]:
arr = np.arange(1, 1000)

In [101]:
%timeit np.power(2, arr)

35 μs ± 4.61 μs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


1. Aggregation of an array

In [102]:
arr = np.arange(1, 11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [103]:
np.add.reduce(arr)  # get the sum of all values within an array

np.int64(55)

In [104]:
np.add.accumulate(arr) # accumulate the result of applying the operator to all elements

array([ 1,  3,  6, 10, 15, 21, 28, 36, 45, 55])

In [105]:
np.multiply.reduce(arr) # get the multiplication of all values within an array

np.int64(3628800)

In [106]:
np.multiply.accumulate(arr)

array([      1,       2,       6,      24,     120,     720,    5040,
         40320,  362880, 3628800])

2. Elementwise arithmetic operation

In [107]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [108]:
# arr+100
# arr-100
# arr*100
# arr/100
arr**2
# 1/arr

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

3. Arithmetic operations using numpy function

In [109]:
# np.add(arr, arr)
# np.subtract(arr, arr)
# np.multiply(arr, arr)
# np.divide(arr, arr)
np.divmod(arr, arr)

(array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1]), array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0]))

In [110]:
# np.sqrt(arr)
# np.log(arr)
np.power(3, arr)
# np.mod(arr, arr)
# np.abs(arr)
# np.exp(arr)
# np.exp2(arr)

array([    3,     9,    27,    81,   243,   729,  2187,  6561, 19683,
       59049])

In [111]:
# Shape mismatch of an array - this occurs when you perform operations such as addition on arrays of different shapes

a = np.arange(4)

a + np.array([1,2])

ValueError: operands could not be broadcast together with shapes (4,) (2,) 

4. Logical operations

In [112]:
a = np.array([0,1,1,0], dtype = bool)
b = np.array([0,0,1,1], dtype = bool)

# np.logical_or(a,b)
# np.logical_and(a,b)
np.logical_xor(a,b)
# np.logical_not(a)

array([False,  True, False,  True])

5. Comparison operations

In [113]:
a = np.array([1,2,3,4])
b = np.array([1,4,3,6])

# np.array_equal(a,b)  # if 2 arrays have the same values

# np.greater_equal(a,b) # a>=b
np.less(a,b)        #a<b
# np.less_equal(a,b)  #a<=b
# np.not_equal(a,b)   #a!=b
# np.equal(a,b)       #a==b

array([False,  True, False,  True])

6. Bitwise operations

In [114]:
np.binary_repr(10)

# np.bitwise_and(arr>4,arr<10)  # arr>4 and arr<10
# np.bitwise_or(arr==4, arr==10) # arr==4| arr==10
np.bitwise_xor(13, 17)  # arr1^arr2
# np.binary_repr(28)
# np.bitwise_not(arr)   # ~arr

np.int64(28)

6. Trigonometric operations

In [115]:
theta = np.linspace(0, np.pi, 3) # degree in radians
theta

array([0.        , 1.57079633, 3.14159265])

In [116]:
print(np.sin(theta))
print(np.cos(theta))
print(np.tan(theta))

[0.0000000e+00 1.0000000e+00 1.2246468e-16]
[ 1.000000e+00  6.123234e-17 -1.000000e+00]
[ 0.00000000e+00  1.63312394e+16 -1.22464680e-16]


7. Statistical operations

In [117]:
x = np.random.randint(150, 180, (20,))
x

array([154, 172, 168, 153, 167, 169, 151, 176, 165, 177, 162, 161, 175,
       167, 167, 158, 171, 174, 170, 155], dtype=int32)

In [118]:
np.sum(x)  # sum of elements
# np.prod(x) # product of elements
# np.mean(x) # mean of elements
# np.std(x)  # standard deviation
# np.var(x)  # variance
# np.median(x) # median of elements
# np.percentile(x, 75) #compute rank-based statistics of elements
# np.max(x)  # maximum value
# np.min(x)  # minimum value
# np.argmax(x) # determining the index of a max value within the array
# np.argmin(x) # determining the index of the min value within the array

np.int64(3312)

In [119]:
# performing statistical operation on a 2D array

p = np.random.randint(0, 5,(4,3))
p

array([[1, 3, 1],
       [3, 2, 1],
       [0, 4, 1],
       [0, 0, 1]], dtype=int32)

In [120]:
# For a 2D array, specify the axis = 0 to perform this operation vertically
# For a 2D array specify the axis = 1, to perform this operation horizontally

np.sum(p, axis = 1)  # sum of elements
# np.prod(p, axis = 0) # product of elements
# np.mean(p) # mean of elements
# np.std(p)  # standard deviation
# np.var(p)  # variance
# np.median(p) # median of elements
# np.percentile(p, 75) #compute rank-based statistics of elements
# np.max(p)  # maximum value
# np.min(p)  # minimum value
# np.argmax(p) # determining the index of a max value within the array
# np.argmin(p) # determining the index of the min value within the array

array([5, 6, 5, 1])