**ARRAY - ds consisting of elements each identified by at least one array index or key**

Numpy - fundamental package for scientific computing in python
      - stores list of numerical vectors andmatrices in the form of arrays
      - the NumPy package has a large set of routines (built-in fns) for creating, manipulating and transforming NumPy arrays

In [1]:
# Creating a one dimensional array using a list
# using numpy.array() function

import numpy as np

my_list = [1,2,3,4]

Oned_arr = np.array(my_list)

Oned_arr #one dimensional array

array([1, 2, 3, 4])

In [2]:
Oned_arr = np.array(my_list, dtype = 'int32')

Oned_arr

array([1, 2, 3, 4], dtype=int32)

In [3]:
# atrributes of an array

print("Array:", Oned_arr)

print("Data type:", type(Oned_arr))

print("Shape of an array:", Oned_arr.shape) # the shape of an array is similar to an order of a matrix

print("Size of each value in an array in bytes:", Oned_arr.itemsize)

print("Total no of bytes of an array:", Oned_arr.nbytes)

print("Data type of an array:", Oned_arr.dtype)

print("Dimension of an array:", Oned_arr.ndim)

# here the shape (4,) means the array is indexed by a single index which runs from 0 to 4

Array: [1 2 3 4]
Data type: <class 'numpy.ndarray'>
Shape of an array: (4,)
Size of each value in an array in bytes: 4
Total no of bytes of an array: 16
Data type of an array: int32
Dimension of an array: 1


In [4]:
# printing the values of a 1-dimensional array using a for loop

print("The array is ")

for i in Oned_arr:

    print(i, end = ' ')

The array is 
1 2 3 4 

In [5]:
# converting a 1-dimensional array to a list

Oned_arr = Oned_arr.tolist()

print(Oned_arr)

print(type(Oned_arr))

[1, 2, 3, 4]
<class 'list'>


In [6]:
# creating a 2D array 

my_mat = [[1,2,3],[4,5,6],[7,8,9]]

array_2D = np.array(my_mat, dtype = 'int32')

array_2D

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]], dtype=int32)

In [7]:
# atrributes of an array

print("Array:", array_2D)

print("Data type:", type(array_2D))

print("Shape of an array:", array_2D.shape) #the shape of an array is a tuple of integers giving the size of the array along each dimension.

print("Size of each value in an array in bytes:", array_2D.itemsize)

print("Total no of bytes of an array:", array_2D.nbytes)

print("Data type of an array:", array_2D.dtype)

print("Dimension of an array:", array_2D.ndim) # it is a 2D array since it requires the index of a row and column to access any element.

Array: [[1 2 3]
 [4 5 6]
 [7 8 9]]
Data type: <class 'numpy.ndarray'>
Shape of an array: (3, 3)
Size of each value in an array in bytes: 4
Total no of bytes of an array: 36
Data type of an array: int32
Dimension of an array: 2


In [8]:
# looping through a 2D array

lst = []

for i in array_2D:
    for j in i:
        print(j, end = ' ')
    print() # gives an empty line as an output

1 2 3 
4 5 6 
7 8 9 


In [9]:
# converting a 2D array to a list using a .tolist() fn
array_2D = array_2D.tolist()

print(array_2D)

print(type(array_2D))

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]
<class 'list'>


In [10]:
# creating an array using a numpy .arange() fn

a_range = np.arange(6)

print(a_range)

[0 1 2 3 4 5]


In [11]:
a_range1 = np.arange(0,11,2)

print(a_range1)

[ 0  2  4  6  8 10]


In [12]:
# reshaping an array using the .reshape() fn

array = np.arange(6).reshape(3, 2) #3 rows and 2 columns

print(array, "\n")

[[0 1]
 [2 3]
 [4 5]] 



In [13]:
# constructing a 3D array

array = np.arange(8).reshape(2,2,2)

print(array)

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


In [14]:
z = np.arange(0, 16, 2).reshape(2,2,2)
print(z, "\n")

z = z.reshape(-1)  # creates a 1D array
print(z)
print(z.shape)
print(z.ndim, "\n")

[[[ 0  2]
  [ 4  6]]

 [[ 8 10]
  [12 14]]] 

[ 0  2  4  6  8 10 12 14]
(8,)
1 



In [15]:
z = np.arange(0, 16, 2).reshape(2,2,2)
print(z, "\n")

z = z.reshape(1, -1)  # creates a 2D array with a single row
print(z)
print(z.shape)
print(z.ndim, "\n")

[[[ 0  2]
  [ 4  6]]

 [[ 8 10]
  [12 14]]] 

[[ 0  2  4  6  8 10 12 14]]
(1, 8)
2 



In [16]:
z = np.arange(0, 16, 2).reshape(2,2,2)
print(z, "\n")

z = z.reshape(-1, 1)  # creates a 2D array with a single row
print(z)
print(z.shape)
print(z.ndim, "\n")

[[[ 0  2]
  [ 4  6]]

 [[ 8 10]
  [12 14]]] 

[[ 0]
 [ 2]
 [ 4]
 [ 6]
 [ 8]
 [10]
 [12]
 [14]]
(8, 1)
2 



In [17]:
# Creating different types of arrays

import numpy as np

np.random.randint(1, 100) # generating a ranfom integer between 1 and 100

96

In [18]:
print("************One dimensional********\n")

print(np.random.randint(1, 100, size = 10), "\n") # will have a shape of 10

print("************Two dimensional********\n")

print(np.random.randint(1, 100, size = (3,4)), "\n") # 2D array with a shape of (3,4)

************One dimensional********

[ 1 25 64 45 80 48 59 98 17 34] 

************Two dimensional********

[[54 10 16 79]
 [31 27 58 57]
 [33 70 71 94]] 



In [19]:
print("************Three dimensional********\n")

print(np.random.randint(1, 100, size = (3,2,2)), "\n") # will have a shape of (3,2,2)

print("************Four dimensional********\n")

print(np.random.randint(1, 100, size = (4,3,32,64)), "\n") # 2D array with a shape of (4,3,32,64)

************Three dimensional********

[[[18 65]
  [42 19]]

 [[57 80]
  [27 61]]

 [[84 10]
  [37 80]]] 

************Four dimensional********

[[[[51 97 41 ... 44 46 71]
   [87 71 33 ... 32 13 30]
   [ 8 11 13 ... 15 13  4]
   ...
   [98 97 61 ... 76 94 36]
   [30 26 89 ... 87 25 31]
   [ 9 69 98 ... 56 41 60]]

  [[85 14 29 ... 73 40 11]
   [32 80 44 ... 87 73 15]
   [18 21 61 ... 78 99 73]
   ...
   [82  7 74 ... 22 91 34]
   [86 58 85 ... 87 96 52]
   [ 7 35 28 ... 29 79 67]]

  [[25 60 30 ... 45 38 49]
   [78 53 82 ... 94 78 55]
   [12 42 46 ... 20  4 36]
   ...
   [18  5 29 ... 21 65  3]
   [60 96 73 ...  8  8 17]
   [74 26  5 ... 74 32 18]]]


 [[[38 82 40 ... 74 27 33]
   [ 3 47 19 ... 52 65 58]
   [77 37 17 ... 70 66 85]
   ...
   [43 13 44 ... 61 27 54]
   [18 87 62 ... 83 74 69]
   [24 28 20 ... 41 59 22]]

  [[43 77 72 ... 78 97 85]
   [57 61 24 ... 51 37 76]
   [66 55 11 ... 95 67 71]
   ...
   [67 99 43 ... 18 96 81]
   [27 91 97 ... 94 36 46]
   [67 34 38 ... 67 42 16]]

In [20]:
np.random.rand(5)   # creating a 1D array of 5 number between 0 and 1

array([0.3223517 , 0.47634105, 0.2543081 , 0.55622845, 0.77051728])

In [21]:
np.random.rand(5,5)   # creating 2D array of random numbers between 0 and 1 of shape (5,5)

array([[0.70006191, 0.53573619, 0.44453146, 0.80413122, 0.16648535],
       [0.21810117, 0.83495485, 0.2094432 , 0.5664358 , 0.76983902],
       [0.02703794, 0.24024013, 0.84308708, 0.60446149, 0.86348639],
       [0.49025493, 0.77780179, 0.55607835, 0.50951155, 0.08669084],
       [0.39181673, 0.48982903, 0.41262867, 0.57638568, 0.55552775]])

In [22]:
# creating a 1D array of saamples from the "standard normal" distribution between 0 and 1

np.random.randn(10)

array([ 0.80684223,  0.54790831,  2.11242107, -0.80756282, -1.31307009,
       -0.9800264 ,  1.96160138,  0.4451132 ,  1.68853891, -1.22483071])

FUNCTIONS TO CREATE ARRAYS OF DIFFERENT TYPES

In [23]:
np.zeros(5)  # creates a new array of given shape and type, filled with zeros

array([0., 0., 0., 0., 0.])

In [24]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [25]:
np.ones(5)   #creates an array filled with ones

array([1., 1., 1., 1., 1.])

In [26]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [27]:
np.eye(4)   # return a 2D array with ones on the diagonal and zeros somewhere

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [28]:
np.full((3,3), 7)  # return a new array filled with a 'filled value'

array([[7, 7, 7],
       [7, 7, 7],
       [7, 7, 7]])

In [29]:
np.diag([1,2,3])  # constructs a diagonal array or extract diagonal values of a multi-dimensional

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [30]:
np.linspace(0,5,10)   # returns an evenly spaced numbers over a specified interval

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

**DATA TYPE CONVERSION OF AN ARRAY**

In [31]:
randarr = np.random.randint(0, 100, 10)

In [32]:
randarr.dtype

dtype('int32')

In [33]:
randarr.astype('int64')

array([ 3, 70, 11, 56, 19, 71, 46, 89, 88,  8])

In [34]:
randarr.astype('float64')

array([ 3., 70., 11., 56., 19., 71., 46., 89., 88.,  8.])

In [35]:
randarr.astype('str')

array(['3', '70', '11', '56', '19', '71', '46', '89', '88', '8'],
      dtype='<U11')

In [36]:
randarr.astype('complex128')

array([ 3.+0.j, 70.+0.j, 11.+0.j, 56.+0.j, 19.+0.j, 71.+0.j, 46.+0.j,
       89.+0.j, 88.+0.j,  8.+0.j])

**ACCESSING ARRAY VALUES**

In [37]:
# accessing and slicing a 1D array values

import numpy as np

arr_1D = np.arange(1,20,2)

arr_1D

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [38]:
arr_1D[8]   # array indexing

np.int64(17)

In [39]:
arr_1D[-1]  # negative indexing 

np.int64(19)

In [40]:
arr_1D[1:5]   # array slicing - but excludes the 5th index

array([3, 5, 7, 9])

In [41]:
arr_1D[0:5]  # - excludes the 5th index

array([1, 3, 5, 7, 9])

In [42]:
arr_1D[:6]

array([ 1,  3,  5,  7,  9, 11])

In [43]:
arr_1D[0] = 111  # changing an array value
arr_1D

array([111,   3,   5,   7,   9,  11,  13,  15,  17,  19])

In [44]:
arr_1D[5:] = 100  # changing array values from the 5th index
arr_1D

array([111,   3,   5,   7,   9, 100, 100, 100, 100, 100])

In [45]:
arr_1D[0] = 112.12  # if we add a float value to an array with integer
             # values, only the integer part will be included in the list
arr_1D

array([112,   3,   5,   7,   9, 100, 100, 100, 100, 100])

In [46]:
# accessing and slicing a 2D array values

arr_2D = np.array([[5,10,15],[20,25,30],[35,40,45]])

arr_2D

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [47]:
arr_2D[0]  # array indexing

array([ 5, 10, 15])

In [48]:
arr_2D[0][2] # accessing a value in a given row

# in this case first row, last value

np.int64(15)

In [49]:
arr_2D[1,2]  # similar to the example in the cell above

np.int64(30)

In [50]:
arr_2D[:2, 1:]  # accessing values in a portion of an array through slicing

array([[10, 15],
       [25, 30]])

In [51]:
arr_2d = np.arange(50).reshape(5, 10)
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [52]:
arr_2d[0:4, 1:4]

array([[ 1,  2,  3],
       [11, 12, 13],
       [21, 22, 23],
       [31, 32, 33]])

In [53]:
# CREATING AN ARRAY VIEW AND AN ARRAY COPY

# array view is a way to access the same data as an existing array without copying it

arr = np.arange(0, 10)

arr # original array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [54]:
arr_view = arr[5:]  # array view creation

arr_view

array([5, 6, 7, 8, 9])

In [55]:
np.shares_memory(arr, arr_view)  # determining if two arrays share memory reference

True

In [56]:
arr_view[:] = 100

arr_view

array([100, 100, 100, 100, 100])

In [57]:
arr  # changes in the view also apply to the original array

array([  0,   1,   2,   3,   4, 100, 100, 100, 100, 100])

In [58]:
# creating an array copy

arr

array([  0,   1,   2,   3,   4, 100, 100, 100, 100, 100])

In [59]:
arr_copy = arr[5:].copy() # creating an array copy

arr_copy

array([100, 100, 100, 100, 100])

In [60]:
np.shares_memory(arr, arr_copy)  # determining if two arrays share memory reference

False

In [61]:
arr_copy[:] = 120

arr_copy # changes made to the copy array will not affect the original array

array([120, 120, 120, 120, 120])

In [62]:
arr # original array

array([  0,   1,   2,   3,   4, 100, 100, 100, 100, 100])

**NUMPY OPERATIONS**

In [63]:
# Time taken to perform operations with Numpy array is much lesser than the time taken by python built-in sequence

x = range(1, 1000)

%timeit [2**i for i in x]

# %timeit gives us the time taken to execute a python statement or expression

2.71 ms ± 486 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [64]:
arr = np.arange(1, 1000)

In [65]:
%timeit np.power(2, arr)

77.1 μs ± 14.6 μs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


1. Aggregation of an array

In [66]:
arr = np.arange(1, 11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [67]:
np.add.reduce(arr)  # get the sum of all values within an array

np.int64(55)

In [68]:
np.add.accumulate(arr) # accumulate the result of applying the operator to all elements

array([ 1,  3,  6, 10, 15, 21, 28, 36, 45, 55])

In [69]:
np.multiply.reduce(arr) # get the multiplication of all values within an array

np.int64(3628800)

In [70]:
np.multiply.accumulate(arr)

array([      1,       2,       6,      24,     120,     720,    5040,
         40320,  362880, 3628800])

2. Elementwise arithmetic operation

In [71]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [72]:
# arr+100
# arr-100
# arr*100
# arr/100
arr**2
# 1/arr

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

3. Arithmetic operations using numpy function

In [73]:
# np.add(arr, arr)
# np.subtract(arr, arr)
# np.multiply(arr, arr)
# np.divide(arr, arr)
np.divmod(arr, arr)

(array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1]), array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0]))

In [74]:
# np.sqrt(arr)
# np.log(arr)
np.power(3, arr)
# np.mod(arr, arr)
# np.abs(arr)
# np.exp(arr)
# np.exp2(arr)

array([    3,     9,    27,    81,   243,   729,  2187,  6561, 19683,
       59049])

In [75]:
# Shape mismatch of an array - this occurs when you perform operations such as addition on arrays of different shapes

a = np.arange(4)

a + np.array([1,2])

ValueError: operands could not be broadcast together with shapes (4,) (2,) 

4. Logical operations

In [ ]:
a = np.array([0,1,1,0], dtype = bool)
b = np.array([0,0,1,1], dtype = bool)

# np.logical_or(a,b)
# np.logical_and(a,b)
np.logical_xor(a,b)
# np.logical_not(a)

5. Comparison operations

In [ ]:
a = np.array([1,2,3,4])
b = np.array([1,4,3,6])

# np.array_equal(a,b)  # if 2 arrays have the same values

# np.greater_equal(a,b) # a>=b
np.less(a,b)        #a<b
# np.less_equal(a,b)  #a<=b
# np.not_equal(a,b)   #a!=b
# np.equal(a,b)       #a==b

6. Bitwise operations

In [ ]:
np.binary_repr(10)

# np.bitwise_and(arr>4,arr<10)  # arr>4 and arr<10
# np.bitwise_or(arr==4, arr==10) # arr==4| arr==10
np.bitwise_xor(13, 17)  # arr1^arr2
# np.binary_repr(28)
# np.bitwise_not(arr)   # ~arr

6. Trigonometric operations

In [ ]:
theta = np.linspace(0, np.pi, 3) # degree in radians
theta

In [ ]:
print(np.sin(theta))
print(np.cos(theta))
print(np.tan(theta))

7. Statistical operations

In [ ]:
x = np.random.randint(150, 180, (20,))
x

In [ ]:
np.sum(x)  # sum of elements
# np.prod(x) # product of elements
# np.mean(x) # mean of elements
# np.std(x)  # standard deviation
# np.var(x)  # variance
# np.median(x) # median of elements
# np.percentile(x, 75) #compute rank-based statistics of elements
# np.max(x)  # maximum value
# np.min(x)  # minimum value
# np.argmax(x) # determining the index of a max value within the array
# np.argmin(x) # determining the index of the min value within the array

In [79]:
# performing statistical operation on a 2D array

p = np.random.randint(0, 5,(4,3))
p

array([[4, 1, 1],
       [2, 2, 4],
       [3, 3, 4],
       [3, 0, 3]], dtype=int32)

In [80]:
# For a 2D array, specify the axis = 0 to perform this operation vertically
# For a 2D array specify the axis = 1, to perform this operation horizontally

np.sum(p, axis = 1)  # sum of elements
# np.prod(p, axis = 0) # product of elements
# np.mean(p) # mean of elements
# np.std(p)  # standard deviation
# np.var(p)  # variance
# np.median(p) # median of elements
# np.percentile(p, 75) #compute rank-based statistics of elements
# np.max(p)  # maximum value
# np.min(p)  # minimum value
# np.argmax(p) # determining the index of a max value within the array
# np.argmin(p) # determining the index of the min value within the array

array([ 6,  8, 10,  6])

**Fancy indexing and sorting of arrays** - NumPy arrays can also be sliced using boolean or integer arrays(masks) a method known as fancy indexing

In [77]:
arr = np.random.randint(0, 101, size=10)

arr

array([48, 41, 64, 15, 78, 29, 96, 80, 75, 99], dtype=int32)

In [81]:
arr > 35 # boolean array mask

array([ True,  True,  True, False,  True, False,  True,  True,  True,
        True])

In [82]:
arr[arr>35]

array([48, 41, 64, 78, 96, 80, 75, 99], dtype=int32)

In [83]:
b_arr = arr<35

In [85]:
x = arr[b_arr]

x

array([15, 29], dtype=int32)

In [87]:
i = np.array([0,3,5,7])  # integer array mask

In [89]:
# fancy indexing with integer array

arr[i] = 100

arr

array([100,  41,  64, 100,  78, 100,  96, 100,  75,  99], dtype=int32)

**Pseudo random state** - prevents values within the array from changing

In [91]:
rng = np.random.RandomState(42)

x = rng.randint(10, size=(3, 4))

x

array([[6, 3, 7, 4],
       [6, 9, 2, 6],
       [7, 4, 3, 7]], dtype=int32)

counting and analyzing values in an array

In [92]:
x

array([[6, 3, 7, 4],
       [6, 9, 2, 6],
       [7, 4, 3, 7]], dtype=int32)

In [94]:
# count of how many values are less than 6

np.count_nonzero(x<6)

5

In [106]:
# count of how many values are less than 6 in each row

np.sum(x<6, axis = 1)  # np.sum is used to count values using comparison operator

array([2, 1, 2])

In [102]:
# are there any values greater than 8?

np.any(x > 8)

np.True_

In [103]:
# are there any values less than 0?

np.any(x < 0)

np.False_

In [104]:
# are all values less than 10?

np.all(x < 10)

np.True_

**Sorting arrays in numpy: np.sort and np.argsort**

In [107]:
x = np.array([2,1,4,3,5])

np.sort(x)

array([1, 2, 3, 4, 5])

In [109]:
x = np.array([22,11,44,33,55])

i = np.argsort(x)  # np.argsort returns the indices of each value e.g 1 which is the index for the value 11

print(i)

[1 0 3 2 4]


In [111]:
x[i]  # fancy indexing

array([11, 22, 33, 44, 55])

**Sorting along rows and columns**

In [112]:
rand = np.random.RandomState(1)

x = rand.randint(0, 10, (4,6))

print(x)

[[5 8 9 5 0 0]
 [1 7 6 9 2 4]
 [5 2 4 2 4 7]
 [7 9 1 7 0 6]]


In [113]:
# sort ech column of x

np.sort(x, axis = 0)

array([[1, 2, 1, 2, 0, 0],
       [5, 7, 4, 5, 0, 4],
       [5, 8, 6, 7, 2, 6],
       [7, 9, 9, 9, 4, 7]], dtype=int32)

In [114]:
# sort each row of x

np.sort(x, axis = 1)

array([[0, 0, 5, 5, 8, 9],
       [1, 2, 4, 6, 7, 9],
       [2, 2, 4, 4, 5, 7],
       [0, 1, 6, 7, 7, 9]], dtype=int32)

**Array product and Concatenation**

product of arrays using np.matmul and np.dot function

In [126]:
# 1-D array

x = np.array([1,2,3,4])
y = np.array([5,6,7,8])

print(np.matmul(x,y)) # np.matmul is for matrix multiplication while np.dot is for finding the product of 2 arrays

# print(x.dot(y))  # inner product of vectors 

# print(np.dot(x,y))  # inner product of vectors

70


np.dot and np.matmul both give the same result when we use it for a 1-D arra and a 2-D array.
However, the results change when we use a 3-D array or a higher dimensional array

In [127]:
# 2-D array

# for a 2D array, it is the matrix product

a = np.array([[1,0],
              [0,1]])

b = np.array([[4,1],
              [2,2]])

print(a @ b) # similar to np.matmul

# np.matmul(a,b) # a @ b - matrix multpiplication of N dimension

# print(np.dot(a,b)) # inner product vector

[[4 1]
 [2 2]]


In [128]:
# 3-D array

np.random.seed(42)

A = np.random.randint(0, 3, size = (1,4,2))

B = np.random.randint(0, 3, size = (3,2,4))

In [130]:
print("A:\n{}, shape = {}\n B:\n{}, shape = {}".format(A, A.shape,B,B.shape))

A:
[[[2 0]
  [2 2]
  [0 0]
  [2 1]]], shape = (1, 4, 2)
 B:
[[[2 2 2 2]
  [0 2 1 0]]

 [[1 1 1 1]
  [0 0 1 1]]

 [[0 0 0 2]
  [2 2 1 2]]], shape = (3, 2, 4)


In [132]:
# C = np.matmul(A,B)
C = np.dot(A,B)

print("Product C:\n{}, shape = {}".format(C, C.shape))

Product C:
[[[[4 4 4 4]
   [2 2 2 2]
   [0 0 0 4]]

  [[4 8 6 4]
   [2 2 4 4]
   [4 4 2 8]]

  [[0 0 0 0]
   [0 0 0 0]
   [0 0 0 0]]

  [[4 6 5 4]
   [2 2 3 3]
   [2 2 1 6]]]], shape = (1, 4, 3, 4)


concatenating arrays of same dimension

In [133]:
x = np.array([1,2,3])
y = np.array([3,2,1])

np.concatenate([x,y])  # concatenating two 1-D arrays

array([1, 2, 3, 3, 2, 1])

In [135]:
grid = np.array([[1,2,3],
                [4,5,6]])

In [137]:
np.concatenate([grid, grid]) # concatenate along the column axis

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [138]:
np.concatenate([grid, grid], axis = 1)  # concatenate along the row axis

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

concatenating arrays of same dimension - for working with arrays of mixed dimension, we can use np.vstack (vertical stack) and np.hstack (horizontal stack) functions

In [142]:
x = np.array([1,2,3])

grid = np.array([[9,8,7],
                [6,5,4]])

np.vstack([x, grid]) # vertically stack the arrays

array([[1, 2, 3],
       [9, 8, 7],
       [6, 5, 4]])

In [144]:
y = np.array([[99],
              [99]])

np.hstack([grid, y]) # horizontally stack the arrays

array([[ 9,  8,  7, 99],
       [ 6,  5,  4, 99]])

flattening of arrays

In [145]:
a = np.array([[1,2,3],[4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [146]:
a.ravel()  # flattening of 2D array

array([1, 2, 3, 4, 5, 6])

transpose of an array

In [147]:
a.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [149]:
a.T.ravel()  # transpose and flattening of an array silmutaneously

array([1, 4, 2, 5, 3, 6])

resizing an array

In [155]:
z = np.arange(1, 10)

z

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [156]:
np.resize(z, (5,3)) # resizing to shape (5,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [1, 2, 3],
       [4, 5, 6]])

In [159]:
z.reshape((3,3)) # resizing to shape (3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

**BROADCASTING** -  powerful mechanism that allows numpy to work with arrays of different shapes when performing arithmetic operations.

In [160]:
# in the simplest example of broadcasting, the scalar 5 is strecthed to become an array
# with the same shape as np.arangge(3), so that the shapes are compatible for element-by-element addition

np.arange(3) + 5

array([5, 6, 7])

In [164]:
np.ones((3,3)) + np.arange(3)

array([[1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.]])

In [166]:
# Rukes of broadcaasting

# 1. If the arrays do not have the same rank (dimension), prepend the shape of the lower rank array with 1s until
#    both shapes have the same length.

# 2. The 2 arrays are said to be compatible in a dimension if they have the same size in the dimension,
#    or if one of the arrays has size 1 in that dimension

# 3. The arrays can be broadcast together if they are compatible in dimensions

# 4. In any dimension where one array had size 1 and the other had size greater than 1, the first array
#    behaves as if it were copied along that dimension